// src/pages/Audit.tsx
import { useState, useRef } from 'react';
import { db, performAuditAnalysis } from '../firebaseConfig'; 
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { 
  Search, Loader2, ShieldCheck, Mail, Phone, User, Download, 
  Calendar, ArrowRight, AlertTriangle, Building2, MapPin, FileText 
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function Audit() {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const reportRef = useRef<HTMLDivElement>(null);
  const [formData, setFormData] = useState({ 
    bizName: "", 
    location: "", 
    fullName: "", 
    email: "", 
    whatsapp: "" 
  });

  const runAudit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      const aiResponse = await performAuditAnalysis(formData.bizName, formData.location);
      
      if (aiResponse.includes("SYSTEM_ERROR") || aiResponse.includes("CONNECTION_ERROR")) {
        setError(aiResponse);
        setLoading(false);
        return;
      }

      setResult(aiResponse);

      // Save to Firestore
      if (db) {
        try {
          // Save audit data
          await addDoc(collection(db, "audits"), {
            businessName: formData.bizName,
            location: formData.location,
            lead: {
              fullName: formData.fullName,
              email: formData.email,
              whatsapp: formData.whatsapp
            },
            analysis: aiResponse,
            engine: "gemini-2.5-flash",
            timestamp: serverTimestamp()
          });

          // Queue email
          await addDoc(collection(db, "mail"), {
            to: formData.email,
            message: {
              subject: `🔍 Your Smart Marketing Entity Audit: ${formData.bizName}`,
              html: `
                <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 40px;">
                  <div style="background: #facc15; padding: 30px; text-align: center; margin: -40px -40px 30px;">
                    <h1 style="color: #020617; margin: 0; font-size: 24px; font-weight: 900; text-transform: uppercase;">Smart Marketing</h1>
                    <p style="color: #020617; margin: 5px 0 0; font-weight: 700; font-size: 12px; text-transform: uppercase; letter-spacing: 2px;">Entity Audit Report</p>
                  </div>
                  
                  <h2 style="color: #facc15; font-size: 20px; margin-bottom: 10px;">Hi ${formData.fullName},</h2>
                  <p style="color: #94a3b8; font-size: 14px; line-height: 1.6; margin-bottom: 20px;">
                    Your strategic audit for <strong style="color: #fff;">${formData.bizName}</strong> is complete.
                  </p>
                  
                  <div style="background: #1e293b; border-left: 4px solid #facc15; padding: 20px; margin: 20px 0; font-size: 13px; line-height: 1.8; color: #cbd5e1;">
                    ${aiResponse.replace(/\n/g, '<br>').replace(/\*\*/g, '<strong style="color: #fff;">').replace(/\[SECTION\]/g, '<div style="color: #facc15; font-weight: 800; margin-top: 15px; text-transform: uppercase; font-size: 11px;">').replace(/\[H\]/g, '<div style="color: #facc15; font-weight: 700; margin: 10px 0 5px; font-size: 12px;">').replace(/\[FIX\]/g, '<div style="background: rgba(250, 204, 21, 0.1); border: 1px solid rgba(250, 204, 21, 0.3); padding: 10px; border-radius: 6px; margin: 10px 0; color: #facc15; font-weight: 600; font-size: 12px;">ACTION:')}
                  </div>

                  <div style="text-align: center; margin: 30px 0;">
                    <a href="https://calendly.com/motsumitl/30min" 
                       style="display: inline-block; background: #facc15; color: #020617; padding: 15px 30px; 
                              text-decoration: none; font-weight: 800; border-radius: 8px; text-transform: uppercase; 
                              font-size: 12px; letter-spacing: 1px;">
                      Schedule Recovery Call
                    </a>
                  </div>
                  
                  <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 30px; border-top: 1px solid #1e293b; padding-top: 20px;">
                    This audit was generated by Smart Marketing's Hunter AI.<br>
                    © 2025 Smart Marketing. All rights reserved.
                  </p>
                </div>
              `
            }
          });
        } catch (dbErr) {
          console.error("Firestore save error:", dbErr);
        }
      }
      
      setStep(3);
    } catch (err: any) {
      setError(`AUDIT_FAILED: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!reportRef.current) return;
    
    try {
      const canvas = await html2canvas(reportRef.current, { 
        scale: 2, 
        backgroundColor: '#020617',
        useCORS: true,
        logging: false
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`SmartMarketing-Audit-${formData.bizName.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
      alert("PDF generation failed. Please try again.");
    }
  };

  const renderText = (text: string) => {
    if (!text) return null;
    
    return text.split('\n').map((line, i) => {
      // Section headers
      if (line.includes('[SECTION]')) {
        return (
          <div key={i} className="mt-16 mb-8 first:mt-0">
            <h4 className="text-yellow-500 font-black text-2xl uppercase tracking-tight border-b-2 border-yellow-500/30 pb-4">
              {line.replace('[SECTION]', '').trim()}
            </h4>
          </div>
        );
      }
      
      // Fix/Action boxes
      if (line.includes('[FIX]')) {
        const content = line.replace('[FIX]', '').trim();
        return (
          <div key={i} className="bg-yellow-500/10 border-l-4 border-yellow-500 p-6 my-8 rounded-r-2xl">
            <div className="flex items-center gap-2 mb-2 text-yellow-500 font-black uppercase text-xs tracking-widest">
              <AlertTriangle size={14} />
              Strategic Requirement
            </div>
            <p className="text-white font-bold text-base leading-relaxed">{content}</p>
          </div>
        );
      }
      
      // Subheaders [H]
      if (line.startsWith('[H]')) {
        return (
          <h5 key={i} className="text-yellow-500/80 font-bold text-lg mt-8 mb-4 uppercase tracking-wide">
            {line.replace('[H]', '').trim()}
          </h5>
        );
      }
      
      // Regular text with bold formatting
      const parts = line.split(/(\*\*.*?\*\*)/g);
      return (
        <p key={i} className="mb-4 text-slate-300 leading-relaxed text-base">
          {parts.map((part, j) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return (
                <strong key={j} className="text-white font-black bg-yellow-500/20 px-1 rounded">
                  {part.slice(2, -2)}
                </strong>
              );
            }
            return <span key={j}>{part}</span>;
          })}
        </p>
      );
    });
  };

  return (
    <div className="min-h-screen bg-slate-950 pt-32 pb-20 px-6">
      <div className="max-w-6xl mx-auto">
        
        {/* Progress Steps */}
        {step > 1 && (
          <div className="flex justify-center mb-12">
            <div className="flex items-center gap-4">
              {[1, 2, 3].map((s, idx) => (
                <div key={s} className="flex items-center">
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center font-black text-sm ${step >= s ? 'bg-yellow-500 text-slate-950' : 'bg-slate-800 text-slate-500'}`}>
                    {s}
                  </div>
                  {idx < 2 && (
                    <div className="w-12 h-1 bg-slate-800 mx-2">
                      <div className={`h-full bg-yellow-500 transition-all duration-500 ${step > s ? 'w-full' : 'w-0'}`} />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Step 1: Business Info */}
        {step === 1 && (
          <div className="max-w-2xl mx-auto text-center animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="mb-10">
              <span className="text-yellow-500 font-bold uppercase tracking-[0.3em] text-xs">Smart Marketing Protocol</span>
              <h2 className="text-6xl md:text-8xl font-black uppercase tracking-tighter mt-4 mb-6">
                Entity <span className="text-yellow-500">Scan</span>
              </h2>
              <p className="text-slate-400 text-lg max-w-lg mx-auto">
                Discover why AI systems can't find your business and calculate your revenue loss from digital invisibility.
              </p>
            </div>

            <form onSubmit={(e) => { e.preventDefault(); if(formData.bizName && formData.location) setStep(2); }} className="space-y-5">
              <div className="relative group">
                <Building2 className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-yellow-500 transition-colors" size={22} />
                <input 
                  required
                  className="w-full bg-slate-900 border-2 border-slate-800 p-6 pl-14 rounded-2xl outline-none focus:border-yellow-500 transition-all text-lg text-white placeholder:text-slate-600" 
                  placeholder="Business Name"
                  value={formData.bizName} 
                  onChange={(e) => setFormData({...formData, bizName: e.target.value})}
                />
              </div>
              
              <div className="relative group">
                <MapPin className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-yellow-500 transition-colors" size={22} />
                <input 
                  required
                  className="w-full bg-slate-900 border-2 border-slate-800 p-6 pl-14 rounded-2xl outline-none focus:border-yellow-500 transition-all text-lg text-white placeholder:text-slate-600" 
                  placeholder="City / Location (e.g., Pretoria, Sandton)"
                  value={formData.location} 
                  onChange={(e) => setFormData({...formData, location: e.target.value})}
                />
              </div>

              <button 
                type="submit"
                className="w-full bg-yellow-500 text-slate-950 p-6 rounded-2xl font-black uppercase tracking-widest text-lg hover:scale-[1.02] active:scale-[0.98] transition-all shadow-2xl shadow-yellow-500/20 flex items-center justify-center gap-3"
              >
                Begin Analysis
                <ArrowRight size={20} />
              </button>
            </form>
          </div>
        )}

        {/* Step 2: Contact Gate */}
        {step === 2 && (
          <div className="max-w-xl mx-auto animate-in fade-in zoom-in-95 duration-500">
            <div className="p-10 md:p-12 border-2 border-slate-800 rounded-[2.5rem] bg-slate-900/50 backdrop-blur-sm shadow-2xl">
              <div className="text-center mb-10">
                <div className="w-16 h-16 bg-yellow-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <ShieldCheck className="text-yellow-500" size={32} />
                </div>
                <h3 className="text-3xl font-black uppercase text-white mb-2">Secure Your Results</h3>
                <p className="text-slate-400">Enter your details to receive the full strategic analysis and PDF report.</p>
              </div>

              <form onSubmit={runAudit} className="space-y-5">
                <div className="relative group">
                  <User className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-yellow-500 transition-colors" size={20} />
                  <input 
                    required 
                    className="w-full bg-slate-950 border-2 border-slate-800 p-5 pl-14 rounded-2xl text-white outline-none focus:border-yellow-500 transition-all placeholder:text-slate-600" 
                    placeholder="Full Name"
                    value={formData.fullName} 
                    onChange={e => setFormData({...formData, fullName: e.target.value})}
                  />
                </div>

                <div className="relative group">
                  <Mail className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-yellow-500 transition-colors" size={20} />
                  <input 
                    required 
                    type="email"
                    className="w-full bg-slate-950 border-2 border-slate-800 p-5 pl-14 rounded-2xl text-white outline-none focus:border-yellow-500 transition-all placeholder:text-slate-600" 
                    placeholder="Business Email"
                    value={formData.email} 
                    onChange={e => setFormData({...formData, email: e.target.value})}
                  />
                </div>

                <div className="relative group">
                  <Phone className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-600 group-focus-within:text-yellow-500 transition-colors" size={20} />
                  <input 
                    required 
                    type="tel"
                    className="w-full bg-slate-950 border-2 border-slate-800 p-5 pl-14 rounded-2xl text-white outline-none focus:border-yellow-500 transition-all placeholder:text-slate-600" 
                    placeholder="WhatsApp Number"
                    value={formData.whatsapp} 
                    onChange={e => setFormData({...formData, whatsapp: e.target.value})}
                  />
                </div>

                {error && (
                  <div className="bg-red-500/10 border-2 border-red-500/50 p-4 rounded-xl text-red-400 text-sm font-bold text-center">
                    {error}
                  </div>
                )}

                <button 
                  disabled={loading} 
                  className="w-full bg-yellow-500 text-slate-950 py-6 rounded-2xl font-black uppercase tracking-widest text-lg shadow-xl shadow-yellow-500/10 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center justify-center gap-3 mt-6"
                >
                  {loading ? (
                    <>
                      <Loader2 className="animate-spin" size={24} />
                      Analyzing Entity...
                    </>
                  ) : (
                    <>
                      Initiate Critical Audit
                      <ArrowRight size={20} />
                    </>
                  )}
                </button>

                <p className="text-center text-slate-600 text-xs mt-4">
                  By proceeding, you agree to receive your audit report via email and WhatsApp.
                </p>
              </form>
            </div>
          </div>
        )}

        {/* Step 3: Results */}
        {step === 3 && result && (
          <div className="animate-in fade-in duration-1000">
            {/* Action Bar */}
            <div className="bg-yellow-500 p-8 rounded-[2rem] mb-12 text-slate-950 flex flex-col md:flex-row items-center justify-between gap-6 shadow-2xl shadow-yellow-500/20">
              <div className="space-y-1 text-center md:text-left">
                <h3 className="text-3xl font-black uppercase leading-none">Your Verdict is Ready</h3>
                <p className="font-bold text-sm opacity-80">Report dispatched to {formData.email}</p>
              </div>
              <div className="flex gap-4">
                <button 
                  onClick={downloadPDF} 
                  className="bg-slate-950 text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-sm flex items-center gap-3 hover:bg-slate-800 transition-all"
                >
                  <Download size={20}/> Download PDF
                </button>
                <a 
                 
