import React, { useEffect } from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-[#050505] min-h-screen pb-20 animate-fade-in font-sans selection:bg-yellow-500 selection:text-black">
      <header className="relative pt-40 pb-20 border-b border-gray-800 bg-[#0a0a0a]">
        <div className="relative z-10 container mx-auto px-6 max-w-4xl text-center">
          <Link to="/" className="inline-flex text-gray-400 hover:text-yellow-500 items-center gap-2 mb-10 uppercase text-[10px] font-black tracking-[0.2em] transition-colors">
            <ArrowLeft size={16}/> Return to Base
          </Link>
          <div className="flex justify-center mb-6">
            <ShieldCheck className="text-yellow-500" size={48} />
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-black mb-6 uppercase tracking-tighter text-white leading-none">
            Data Governance <br/><span className="text-yellow-500 italic">& API Compliance</span>
          </h1>
          <p className="text-gray-400 text-lg uppercase tracking-widest font-bold mt-8">Effective Date: Current Deployment</p>
        </div>
      </header>

      <article className="container mx-auto px-6 max-w-3xl py-16 text-gray-300 text-base md:text-lg leading-relaxed space-y-12">
        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">1. Introduction & Regulatory Framework</h2>
          <p>
            At Happy Hunter Digital ("we", "us", or "our"), we operate in an ecosystem driven by data intelligence. Absolute digital dominance requires absolute data sovereignty and algorithmic trust. This protocol details our strict parameters for the collection, utilization, and cryptographic security of your data.
          </p>
          <p className="mt-4">
            We operate in strict adherence to the <strong className="text-white">Protection of Personal Information Act (POPIA)</strong> of South Africa, and international standards including the <strong className="text-white">GDPR (Europe)</strong> and <strong className="text-white">CCPA (California)</strong>.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">2. Telemetry & Data Collection</h2>
          <p>When you interface with our digital properties (happyhunterdigital.com) or deploy our Smart Marketing Scan, we collect the following vectors of information under the principle of Data Minimization:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li><strong className="text-white">Entity Data:</strong> Business names, verified email addresses, WhatsApp contact numbers, and physical operational coordinates.</li>
            <li><strong className="text-white">Diagnostic Data:</strong> Results generated by our AI Audit tools, including "Digital Survival Scores" and perceived market vulnerabilities.</li>
            <li><strong className="text-white">Automated Signals:</strong> IP addresses and user-agent strings required to optimize the generative search experience. IP data is truncated before storage.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">3. API Compliance & Platform Integration</h2>
          <p>Our architecture interfaces with enterprise Social Media Developer Platforms (Meta, X, LinkedIn). To maintain API compliance and prevent platform flagging, we enforce:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li><strong className="text-white">Data Minimization (Strict Scoping):</strong> We request only the minimum specific scopes required for protocol execution.</li>
            <li><strong className="text-white">Cryptographic Authentication:</strong> We mandate OAuth 2.0. All acquired access tokens are stored using AES-256 encryption at rest.</li>
            <li><strong className="text-white">Platform Adherence:</strong> We follow the "Breaking Change" and "Data Use" policies of our API partners, prohibiting unauthorized surveillance or tracking.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">4. Utilization of Intelligence</h2>
          <p>We do not hoard data. Information is collected specifically to execute operational mandates:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li>To compile and deliver your bespoke Forensic Intelligence Reports.</li>
            <li>To inject verified schema markup into the Google Knowledge Graph on your behalf.</li>
            <li>To initiate secure communication protocols. <strong className="text-yellow-500">We do not, and will never, sell your raw data to independent data brokers.</strong></li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">5. Entity Sovereignty (Your Rights)</h2>
          <p>Under GDPR, CCPA, and POPIA frameworks, you retain total programmatic ownership of your digital footprint, including rights to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li>Request a programmatic export of the telemetry data we hold on your entity.</li>
            <li>Demand the immediate, automated erasure of your records from our databases via our delete endpoints ("The Right to be Forgotten").</li>
            <li>Revoke consent for WhatsApp or email communications instantly.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">6. Initiate Contact</h2>
          <p>To execute a data request or question our security architecture, ping our command center directly:</p>
          <div className="bg-[#111827] border border-gray-800 p-6 rounded-2xl mt-6">
            <p className="font-mono text-sm text-yellow-500 mb-2">Primary Contact Vector:</p>
            <p className="font-bold text-white">motsumitl@happyhunterdigital.com</p>
            <p className="font-bold text-white mt-2">+27 (0) 60 101 6673</p>
          </div>
        </section>
      </article>
    </div>
  );
};
