import React, { useEffect } from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-[#050505] min-h-screen pb-20 animate-fade-in font-sans selection:bg-yellow-500 selection:text-black">
      <header className="relative pt-40 pb-20 border-b border-gray-800 bg-[#0a0a0a]">
        <div className="relative z-10 container mx-auto px-6 max-w-4xl text-center">
          <Link to="/" className="inline-flex text-gray-400 hover:text-yellow-500 items-center gap-2 mb-10 uppercase text-[10px] font-black tracking-[0.2em] transition-colors">
            <ArrowLeft size={16}/> Return to Base
          </Link>
          <div className="flex justify-center mb-6">
            <ShieldCheck className="text-yellow-500" size={48} />
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-black mb-6 uppercase tracking-tighter text-white leading-none">
            Data Governance <br/><span className="text-yellow-500 italic">& Privacy Protocol</span>
          </h1>
          <p className="text-gray-400 text-lg uppercase tracking-widest font-bold mt-8">Effective Date: 20 February 2026</p>
        </div>
      </header>

      <article className="container mx-auto px-6 max-w-3xl py-16 text-gray-300 text-base md:text-lg leading-relaxed space-y-12">
        
        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">1. Introduction</h2>
          <p>
            At Happy Hunter Digital ("we", "us", or "our"), we operate in an ecosystem driven by data intelligence. However, we believe that absolute digital dominance requires absolute data sovereignty. This Privacy Policy details our protocols for the collection, utilization, and cryptographic security of your personal and business data.
          </p>
          <p className="mt-4">
            We adhere strictly to the <strong className="text-white">Protection of Personal Information Act (POPIA)</strong> of South Africa, and international standards including the <strong className="text-white">GDPR</strong>.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">2. Telemetry & Data Collection</h2>
          <p>When you interface with our digital properties (happyhunterdigital.com) or deploy our Smart Marketing Scan, we collect the following vectors of information:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li><strong className="text-white">Entity Data:</strong> Business names, verified email addresses, WhatsApp contact numbers, and physical operational coordinates.</li>
            <li><strong className="text-white">Diagnostic Data:</strong> Results generated by our AI Audit tools, including "Digital Survival Scores" and perceived market vulnerabilities.</li>
            <li><strong className="text-white">Automated Signals:</strong> IP addresses, user-agent strings, and interaction heatmaps required to optimize the generative search experience.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">3. Utilization of Intelligence</h2>
          <p>We do not hoard data. Information is collected specifically to execute operational mandates:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li>To compile and deliver your bespoke Forensic Intelligence Reports.</li>
            <li>To inject verified schema markup into the Google Knowledge Graph on your behalf.</li>
            <li>To initiate secure communication protocols via email or WhatsApp regarding our Agentic Revenue Systems.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">4. Third-Party Integration</h2>
          <p>
            To execute our architecture, data is routed through highly secure, enterprise-grade LLMs and APIs (e.g., Google Gemini, Google Places API, Firebase Firestore). <strong className="text-yellow-500">We do not, and will never, sell your raw data to independent data brokers.</strong>
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">5. User Sovereignty (Your Rights)</h2>
          <p>Under POPIA and GDPR frameworks, you retain total ownership of your digital footprint. You have the right to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-gray-400">
            <li>Request a full export of the telemetry data we hold on your entity.</li>
            <li>Demand the immediate erasure of your records from our Firestore databases ("The Right to be Forgotten").</li>
            <li>Revoke consent for WhatsApp or email communications at any time.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black text-white uppercase tracking-tighter mb-4 border-l-4 border-yellow-500 pl-4">6. Initiate Contact</h2>
          <p>To execute a data request or question our security architecture, ping our command center directly:</p>
          <div className="bg-[#111827] border border-gray-800 p-6 rounded-2xl mt-6">
            <p className="font-mono text-sm text-yellow-500 mb-2">Primary Contact Vector:</p>
            <p className="font-bold text-white">motsumitl@happyhunterdigital.com</p>
            <p className="font-bold text-white mt-2">+27 (0) 60 101 6673</p>
          </div>
        </section>

      </article>
    </div>
  );
};
